---
# yamllint disable rule:line-length
name: Publish Docker images

"on":
  push:
    branches: ["main"]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG=$(git rev-parse --short=6 HEAD)
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/netxms-server:${{ steps.vars.outputs.tag }}  # yamllint disable-line rule:line-length
            ghcr.io/${{ github.repository_owner }}/netxms-server:latest  # yamllint disable-line rule:line-length

      - name: Build and push agent image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.agent
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/netxms-agent:${{ steps.vars.outputs.tag }}  # yamllint disable-line rule:line-length
            ghcr.io/${{ github.repository_owner }}/netxms-agent:latest  # yamllint disable-line rule:line-length
